[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true
ffi = true
fs_permissions = [{ access = "read", path = "./"}]
evm_version="cancun"
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
